if not defined in_subprocess (cmd /k set in_subprocess=y ^& %0 %*) & exit )
echo off
cls
echo _________________
echo wifi auto_connect
echo  by AnCarsenat
echo _________________
powershell.exe -Command "Start-Sleep -MilliSeconds 1500"
cls
:main_menu
echo Choose action to realise :
echo 1 : Show wifis
echo 2 : Connect
echo 3 : Advanced Connect
echo 4 : Setup Auto-Connect
echo 5 : Show wifi password
choice /M "" /N /C 12345
goto menu%errorlevel%

:menu6
echo Head back to main menu
choice /M "" 
if "%errorlevel%"=="1" (
cls
goto main_menu)

:menu1
Netsh wlan show profiles
goto menu6

:menu2
set /p profile_name="Wifi-Name : "
netsh wlan connect %profile_name%
goto menu6

:menu3
echo Menu currently unavailable
goto menu6

:menu4
echo Auto connect starting
goto auto-connect-writer
goto menu6

:menu5
echo Show-Hide password
set /p wifi_name="Wifi name : " 

echo rem File generated by batch > output.txt
FOR /F "tokens=*" %%a in ('netsh wlan show profile name= "%wifi_name%" key=clear') do echo %%a >> output.txt
type output.txt
@pause

del output.txt 
goto menu6

:menu7
setlocal
set none=none
set /p wifi_name=%none%
echo Import-Export wifi configs
set /p wifi_name="Wifi name : " 
echo %none%
echo %wifi_name%

endlocal


rem netsh wlan export profile "%wifi_name%" key=clear %cd%\wifiConfigs

if %wifi_name%

rem netsh wlan add profile filename="" user=all











:auto-connect-writer
echo C:\Users\antoinecarsenat\Desktop
set /p file_directory="File dir (Ex: C:\a\b\c\autoconnect or start) : "

if "%file_directory%"=="start" ( 
echo Setting directory to startup folder
set /p file_name="File name : " )

if defined file_name (
set file_directory="%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\%file_name%-autoconnect")

set /p wifi_name="Wifi name : "

(
echo rem file generated by batch file used to connect to networks
echo netsh wlan connect %wifi_name%
) >%file_directory%.bat
goto menu6


