if not defined in_subprocess (cmd /k set in_subprocess=y ^& %0 %*) & exit )
echo off
cls
echo _________________
echo wifi auto_connect
echo  by AnCarsenat
echo _________________
powershell.exe -Command "Start-Sleep -MilliSeconds 1500"
cls
:main_menu
echo Choose action to realise :
echo 1 : Show wifis
echo 2 : Connect
echo 3 : Advanced Connect
echo 4 : Setup Auto-Connect
echo 5 : Show wifi password
echo 6 : Import-Export config
choice /M "" /N /C 123456
goto menu%errorlevel%

:menu10
echo Head back to main menu
choice /M "" 
if "%errorlevel%"=="1" (
cls
goto main_menu)

:menu1
Netsh wlan show profiles
goto menu10

:menu2
set /p profile_name="Wifi-Name : "
netsh wlan connect %profile_name%
goto menu10

:menu3
echo Menu currently unavailable
goto menu10

:menu4
echo Auto connect starting
goto auto-connect-writer
goto menu10

:menu5
echo Show-Hide password
set /p wifi_name="Wifi name : " 

echo rem File generated by batch > output.txt
FOR /F "tokens=*" %%a in ('netsh wlan show profile name= "%wifi_name%" key=clear') do echo %%a >> output.txt
type output.txt
@pause

del output.txt 
goto menu10

:menu6

echo Import-Export wifi configs
echo Import: 1
echo Export: 2
echo ShowConfigs: 3
echo Autoconnect: 4
choice /M "" /C 1234
goto menu6%errorlevel%
rem ---------------IMPORT------------
:menu61
echo IMPORT
dir %cd%\wifi-configs
setlocal
set wifi_name=""
set /p wifi_name="Wifi name : " 
echo wifi is %wifi_name%
if "%wifi_name%"=="" (echo Wifi is none
powershell.exe -Command "Start-Sleep -MilliSeconds 500"
cls
goto menu6)
echo importing
netsh wlan add profile filename="%cd%\wifi-configs\Wi-Fi-%wifi_name%.xml" user=all
@pause
endlocal
cls
goto menu10
rem -----------------EXPORT-------------------
:menu62
setlocal
set wifi_name=""
set /p wifi_name="Wifi name : " 
echo wifi is %wifi_name%
if "%wifi_name%"=="" (echo Wifi is none
powershell.exe -Command "Start-Sleep -MilliSeconds 500"
cls
goto menu6)

echo exporting
netsh wlan export profile name="%wifi_name%" key=clear folder="%cd%\wifi-configs"
@pause
endlocal
cls
goto menu10
rem ----------------SHOW CONFIGS--------------
:menu63
echo _____________Configs_____________
dir %cd%\wifi-configs
@pause
cls
goto menu6
rem ----------------AUTOCONNECT---------------
:menu64
echo C:\Users\antoinecarsenat\Desktop
set /p config_file_name="Config File name (Ex: A_Wifi_Name_In_Configs) : "
set /p file_directory="Autoconnect File dir (Ex: C:\a\b\c\autoconnect or start) : "

if "%file_directory%"=="start" ( 
echo Setting directory to startup folder
set /p file_name="File name : ")
if defined file_name (
set file_directory="%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\%file_name%-autoconnect")


(
echo rem file generated by batch file used to connect to networks
echo netsh wlan add profile filename="%cd%\wifi-configs\Wi-Fi-%config_file_name%.xml" user=all
echo netsh wlan connect %config_file_name%
) >%file_directory%.bat
echo File created (operation success)
powershell.exe -Command "Start-Sleep -MilliSeconds 1500"
cls
goto menu6
-----------------------END OF CONFIG WIFI WRITER -------------


rem netsh wlan export profile name="%wifi_name%" key=clear folder="%cd%\wifi-configs"
rem netsh wlan add profile filename="" user=all


rem ----- AUTOCONNECT WRITER --------
:auto-connect-writer
echo C:\Users\antoinecarsenat\Desktop
set /p file_directory="File dir (Ex: C:\a\b\c\autoconnect or start) : "

if "%file_directory%"=="start" ( 
echo Setting directory to startup folder
set /p file_name="File name : " )

if defined file_name (
set file_directory="%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\%file_name%-autoconnect")

set /p wifi_name="Wifi name : "

(
echo rem file generated by batch file used to connect to networks
echo netsh wlan connect %wifi_name%
) >%file_directory%.bat
goto menu6





